修复离职用户仍然收到密码修改邮件缺陷
TencentBlueKing/bk-user pull request #1977
Opened 2024-11-07 02:18 UTC by bevis-canway

### Description

Fixes # (issue)

### Checklist

- [ ] 填写 PR 描述及相关 issue (write PR description and related issue)
- [ ] 代码风格检查通过 (code style check passed)
- [ ] PR 中包含单元测试 (include unit test)
- [ ] 单元测试通过 (unit test passed)
- [ ] 本地开发联调环境验证通过 (local development environment verification passed)

2024-11-11 01:42 UTC, narasux commented on src/api/bkuser_core/common/notifier.py
> +def send_mail(receiver__username: List[str], message: str, sender: str = None, title: str = None, ):
违反 Python 变量命名规则，从名字也看不出来是列表

2024-11-11 01:43 UTC, narasux commented on src/api/bkuser_core/profiles/tasks.py
> +
这里为什么需要空行

2024-11-11 01:53 UTC, narasux requested changes
思路是让 cmsi 组件根据 receiver__username 参数而不是 receiver 参数发送邮件，为什么需要调整 send_mail 的封装呢，直接修改 send_mail_params 中使用的参数即可

2024-11-26 10:01 UTC, bevis-canway commented on src/api/bkuser_core/common/notifier.py
> +def send_mail(receiver__username: List[str], message: str, sender: str = None, title: str = None, ):
已修改为receiver_usernames

2024-11-26 10:04 UTC, bevis-canway commented
cmsi是会根据receiver__username里面的用户列表进行校验，这里传的是用户名，而receivers传的是用户邮箱列表。

2024-11-26 14:39 UTC, merged